MedicalAPI/Config/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

#ADMIN
    url(r'^admin/', admin.site.urls),

#DJANGO-HOME
    url(r'^$', views.homepage),
    url(r'^next/$', views.nextpage),


#MEDICAL-APP
    url(r'^diseases/', include('medical.urls')),


#PATIENT-APP
    url(r'^patients/', include('patients.urls')),

]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MedicalAPI/medical/urls.py
from django.conf.urls import url
from . import views


app_name = "medical"

urlpatterns = [
    url(r'^$', views.disease_list, name="list"),
    url(r'^create/$', views.disease_create, name="create"),
    url(r'^(?P<DrName>[\w-]+)/$',views.disease_detail, name="detail"),
]

MedicalAPI/patients/urls.py
from django.conf.urls import url
from . import views

app_name = 'patients'

urlpatterns = [
   url(r'^signup/$', views.signup_view, name="signup"),
   url(r'^login/$', views.login_view, name="login"),
   url(r'^logout/$', views.logout_view, name="logout"),
]

MedicalAPI/medical/models.py
from django.db import models

# Create your models here.

class Disease(models.Model):
	DiseaseName = models.CharField(max_length=50)

	DrName = models.SlugField()

	symptom = models.TextField()

	date = models.DateTimeField(auto_now_add=True)

	profilePicture = models.ImageField(default='default.png', blank=True)


	def __str__(self):
		return "> {}".format(self.DiseaseName)		#here we giving output to admin page from database

	def  sort_symptom(self):
		return self.symptom[:50] + ' .....'

MedicalAPI/patients/models.py
from django.db import models

# Create your models here.

MedicalAPI/Config/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
	#return HttpResponse("This is the HomePage of >> CORE_view")
	return render(request,'homepage.html')


def nextpage(request):
	#return HttpResponse("next >> home page")
	return render(request,'nextpage.html')

MedicalAPI/medical/views.py
from django.shortcuts import render
from .models import Disease
from django.http import HttpResponse



def disease_list(request):
	diseases = Disease.objects.all().order_by('date');
	#return HttpResponse(diseases)
	return render(request,'medical/disease_list.html',{'diseases':diseases})


def disease_detail(request, DrName):
	disease = Disease.objects.get(DrName=DrName)
	return render(request, 'medical/disease_detail.html', {"disease":disease})


def disease_create(request):
	return render(request, 'medical/disease_create.html')

MedicalAPI/patients/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.

def signup_view(request):
	if request.method =='POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()

			#log the user in

			login(request, user)
			return 	redirect(request,'/')
	else:
		form = UserCreationForm()

	return render(request,'patients/signup.html',{'form':form})

#************************************************************


def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			#log the user in

			user = form.get_user()
			login(request, user)
			return redirect('/')


	else:
		form = AuthenticationForm()

	return render(request,'patients/login.html',{'form':form })


def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('medical:list')

MedicalAPI/medical/templates/medical/disease_create.html
disease_create.html

MedicalAPI/medical/templates/medical/disease_detail.html
{% extends 'base.html' %}

{% block block_name1 %}

<div class="disease-detail">
	<div class="disease">

		<img src="{{ disease.profilePicture.url }}">
		<h1>{{ disease.DiseaseName }}</h1>
		<br>
		<h2>{{ disease.DrName }}</h2>
		<p>{{ disease.symptom }}</p>
		<p>{{ disease.date }}</p>

	</div>
</div>
{% endblock %}

MedicalAPI/medical/templates/medical/disease_list.html
{% extends 'base.html' %}

{% block block_name1 %}

	<h1>Diseases List</h1>
	<br>
	<div class="diseases">

	{% for disease in diseases %}

		<div class="disease">
			<h2><a href="{% url 'medical:detail' DrName=disease.DrName %}">
			{{ disease.DiseaseName }} :</a></h2>
			
			<p><strong>{{ disease.DrName }}</strong> [<i>{{ disease.date }}</i>]</p>
			
			<p>{{ disease.sort_symptom }}</p>
		 
		</div>
		{% endfor %}
	</div>

{% endblock %}

MedicalAPI/patients/templates/patients/login.html
{% extends 'base.html' %}

{% block block_name1 %}
 <h1>Log in</h1>
 <form class="site-form" action="{% url 'patients:login' %}" method="post">
 	{% csrf_token %}
 	{{ form }}
 	<input type="submit" name="" value="Login">

 </form>
{% endblock %}

MedicalAPI/patients/templates/patients/signup.html
{% extends 'base.html' %}

{% block block_name1 %}
 <h1>Signup</h1>
 <form class="site-form" action="/patients/signup" method="post">
 	{{ form }}
 	<input type="submit" name="" value="Signup">


 </form>
{% endblock %}

MedicalAPI/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>

<html>
<head>
	<title> Symptoms </title>
	<link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
	<div class="wrapper">
		<h1><a href="{% url 'medical:list' %}"><img src="{% static 'logo.png' %}" /></a> </h1>
		<nav>
			<ul>
				<li>
					<form class="logout-link" action="{% url 'patients:logout' %}" method="post">
						{% csrf_token %}
						<button type="submit">Logout</button>
						
					</form>
				</li>
			</ul>
		</nav>
		{% block block_name1 %}
		{% endblock %}
		
	</div>

</body>
</html> 

MedicalAPI/templates/homepage.html
<!DOCTYPE html>
<html>
<head>
	<title>HOME**PAGE</title>
</head>
<body>

<h1>Home_Page</h1>
<h3><p>Wellcome to Django</p></h3>

</body>
</html>

MedicalAPI/templates/nextpage.html
<!DOCTYPE html>
<html>
<head>
	<title> PAGE 1</title>
</head>
<body>

<h1>Next_Page</h1>
<h3><p>Wellcome to Django next PAGE .</p></h3>

</body>
</html>